### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by heisenberg2980** [ManiMatter/decluttarr#1]
I am getting this error when trying to start the container using docker-compose:

```
decluttarr  | [INFO]: Application Started!
decluttarr  | [INFO]: 
decluttarr  | [INFO]: *** Current Settings ***
decluttarr  | [INFO]: True | Removing failed downloads
decluttarr  | [INFO]: True | Removing stalled downloads
decluttarr  | [INFO]: True | Removing downloads missing metadata
decluttarr  | [INFO]: True | Removing orphan downloads
decluttarr  | [INFO]: True | Removing downloads belonging to unmonitored TV shows/movies
decluttarr  | [INFO]: 
decluttarr  | [INFO]: Running every: 0 days 0 hours 10 minutes
decluttarr  | [INFO]: Permitted number of times before stalled/missing metadata downloads are removed: 3
decluttarr  | [INFO]: Downloads with this tag will be skipped: Don't Kill If Stalled
decluttarr  | [INFO]: 
decluttarr  | [INFO]: *** Configured Instances ***
decluttarr  | [INFO]: Radarr: http://192.168.0.208:7878/api/v3
decluttarr  | [INFO]: Sonarr: http://192.168.0.208:8989/api/v3
decluttarr  | [INFO]: qBittorrent: http://192.168.0.208:8080/api/v2
decluttarr  | [INFO]: 
decluttarr  | [INFO]: ##################################################
decluttarr  | [INFO]: [LOG_LEVEL = INFO]: Only logging changes (switch to VERBOSE for more info)
decluttarr  | [ERROR]: Error making API request to http://192.168.0.208:8080/api/v2/torrents/tags: 403 Client Error: Forbidden for url: http://192.168.0.208:8080/api/v2/torrents/tags
decluttarr  | TypeError: argument of type 'NoneType' is not iterable
```

This is my docker-compose.yaml file:

```
# decluttarr - Keeps radarr and sonarr download queues free of stalled and redundant items
  decluttarr:
    container_name: decluttarr
    image: ghcr.io/manimatter/decluttarr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .en
      # General
      - LOG_LEVEL=INFO
      # Features 
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_STALLED=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_ORPHANS=True
      - REMOVE_UNMONITORED=True
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG="Don't Kill If Stalled"
      # Radarr
      - RADARR_URL=http://192.168.0.208:7878
      - RADARR_KEY=***KEY_REMOVED***
      # Sonarr
      - SONARR_URL=http://192.168.0.208:8989
      - SONARR_KEY=***KEY_REMOVED***
      # qBitorrent
      - QBITTORRENT_URL=http://192.168.0.208:8080
```
