### ISSUE TITLE
Movie mismatch errors not being included in Radar errors to clean up

### ISSUE THREAD

**Issue by imran0** [ManiMatter/decluttarr#171]
In my radarr error config I’ve removed all error strings which according to documentation means all entries with errors will be removed however I can see there are two items in my activity list in radarr with errors like this

Downloaded - Unable to Import Automatically
Halloween 4 The Return of Michael Myers (1988) [BluRay] [1080p] ...
Movie title mismatch, automatic import is not possible. Manual Import required.

Is there a reason why this isn’t picked up by the script?

**Comment by ManiMatter** [comment]
Can you pls share debug logs?

**Comment by imran0** [comment]
Not sure how much you want me to go back, but here is the most recent run:

[VERBOSE]: Queue clean-up complete!
[VERBOSE]: --------------------------------------------------
[VERBOSE]: Cleaning queue on Radarr SDR RD:
[VERBOSE]: >>> Queue is clean.
[VERBOSE]: >>> Rescan: All missing items have recently been scanned for, thus nothing to rescan.
[VERBOSE]: >>> Rescan: All cutoff items have recently been scanned for, thus nothing to rescan.
[VERBOSE]: Cleaning queue on Sonarr 4K RD:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]: >>> Running a scan for 1 missing items:
Biography: WWE Legends (Season 3 / Episode 7 / Aired: 2023-03-26): Charlotte Flair
[VERBOSE]: >>> Running a scan for 1 cutoff items:
Rick and Morty (Season 2 / Episode 3 / Aired: 2015-08-09): Auto Erotic Assimilation
[VERBOSE]: 
[VERBOSE]: Queue clean-up complete!

The queue items sit in my Radarr instance.
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/5eacdeb2-e6c0-4a3f-bc1d-effa0fd581e8">
They have been there for a few days now. I can confirm it is connected to the correct instance of Radarr (I run multiple)

**Comment by ManiMatter** [comment]
Sorry, what I meant with debug logs is this:
- turn off all jobs other than the one that deals with broken imports
- switch log-level to "DEBUG"
- run for one cycle and post the full logs to a paste bin and link them here

**Comment by imran0** [comment]
Here is my pastebin:
https://pastebin.com/GWLD4Yf9

**Comment by ManiMatter** [comment]
> 2024-10-14T19:21:52.408080768Z [DEBUG]: remove_failed_imports/queue IN: **empty**

What strikes me is that on Row 67 it says that the queue is empty, but on Row 62 there are queue items listed.

I know the difference between the two calls (and the difference is intentionally), but in theory it should not matter.

Three questions:
1) Are you using any special Radarr (and not the official one from `lscr.io/linuxserver/radarr:nightly`
2) Any special network setups I should be aware?
3) Can you disable REMOVE_FAILED_IMPORTS and enable REMOVE_SLOW instead, and post the logs? I want to see if the queue reads correctly over there (it is the same code, in theory queue should also fail there)

**Comment by imran0** [comment]
1. I'm using `https://lscr.io/linuxserver/radarr:latest` image
2. Nope, using this in a docker container, they all are in the same network that docker creates
3. Done, the logs can be found [here](https://pastebin.com/72b3ZHPw) (it still hasnt removed the downloads)

**Comment by ManiMatter** [comment]
Thanks for the inputs.
The logs confirm what I suspected:
> 2024-10-16T20:16:41.918263759Z [DEBUG]: remove_slow/queue IN: empty

It's not about the REMOVE_FAILED_IMPORTS job, but actually any job seems to return a empty queue.
I wonder why.

What happens if you switch to the nightly radarr version?


to help debug this, I have created a new version that has specific logs that hopefully help us ringfence the problem. Can you pls pull fix-empty-queue image and provide the debug logs?

**Comment by imran0** [comment]
I have switched to the radarr nightly and your debug image. Here is the debug logs: https://pastebin.com/KZMLnhex

**Comment by ManiMatter** [comment]
> 2024-10-16T20:56:46.107101542Z [DEBUG]: DEBUG get_arr_records record_count: **0**
> 2024-10-16T20:56:46.107199839Z [DEBUG]: remove_slow/queue IN: empty

why the heck is it 0????
can you maybe share a screenshot of your radarr queue?

**Comment by imran0** [comment]
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/a6429492-5289-4425-bee8-c3c4ce18244d">
According to this its downloading, but yesterday it was just failed to import. Not sure if its the same releases or not (I'm fairly certain they are, as I cant see anything in my recent downloads matching it)

**Comment by ManiMatter** [comment]
Ok, I think i know the reason.

Look at the "Movie" column. It's not a movie name, its actually a file name.
That means that this file can't be linked (for whatever reason) to a Movie. 

Let's say the movie was "Halloween 4" or whatever; if it was able to link it, you'd see "Halloween 4" written there, and not what you currently see.

This is why the "normal" queue command doesn't pick those up, but they are found by 
`2024-10-16T20:56:46.085960086Z [DEBUG]: http://radarr-sdr-rd:7878 "GET /radarr-sdr-rd/api/v3/queue?includeUnknownMovieItems=True HTTP/11" 200 None`


If you turn on "REMOVE_ORPHANS" these will be killed.

can you pls try? If yes - this ticket can be closed (suggest you switch back to decluttarr:latest)

**Comment by imran0** [comment]
So I have switched remove orphaned to TRUE and reverted all my other settings. It still doesn't work.
https://pastebin.com/WD2N4pr0

Here is my feature config if it helps
```
      REMOVE_TIMER: 10
      REMOVE_FAILED: "False"
      REMOVE_FAILED_IMPORTS: "True"
      REMOVE_METADATA_MISSING: "True"
      REMOVE_MISSING_FILES: "True"
      REMOVE_ORPHANS: "True"
      REMOVE_SLOW: "False"
      REMOVE_STALLED: "False"
      REMOVE_UNMONITORED: "False"
      RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 1, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 1, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'
```

**Comment by ManiMatter** [comment]
can you pls 
- from the jobs, only keep REMOVE_ORPHANS: True (without quotation marks)
- again switch to debug level
- provide logs

**Comment by imran0** [comment]
Using the following
```
      LOG_LEVEL: DEBUG #VERBOSE
      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: "False"
      REMOVE_FAILED_IMPORTS: False
      REMOVE_METADATA_MISSING: "False" #"True"
      REMOVE_MISSING_FILES: "False" #"True"
      REMOVE_ORPHANS: True
      REMOVE_SLOW: "False"
      REMOVE_STALLED: "False"
      REMOVE_UNMONITORED: "False"
```

When staring the docker I get this error:
> The Compose file './docker-compose.yml' is invalid because:
services.decluttarr-sdr.environment.REMOVE_FAILED_IMPORTS contains false, which is an invalid type, it should be a string, number, or a null

**Comment by ManiMatter** [comment]
```
 decluttarr:
   <<: *common-keys-media
   image: ghcr.io/manimatter/decluttarr:dev
   container_name: decluttarr
   environment:
     <<: *default-tz-puid-pgid
     # General
     LOG_LEVEL: INFO
     # Features 
     REMOVE_TIMER: 10
     REMOVE_FAILED: True
     REMOVE_FAILED_IMPORTS: True
     REMOVE_METADATA_MISSING: True
     REMOVE_MISSING_FILES: True
     REMOVE_ORPHANS: True
     REMOVE_SLOW: True
     REMOVE_STALLED: True
     REMOVE_UNMONITORED: True
     RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 1},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 1}
        }'
     PERMITTED_ATTEMPTS: 3
     NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
     REMOVE_SLOW: True
     MIN_DOWNLOAD_SPEED: 100     
     FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]'
     # Radarr
     RADARR_URL: http://radarr:7878
     RADARR_KEY: $RADARR_API_KEY
     # Sonarr
     SONARR_URL: http://sonarr:8989
     SONARR_KEY: $SONARR_API_KEY
     # qBitorrent
     QBITTORRENT_URL: http://qbittorrent:8080
```


Above is my docker-compose config that does work for me. I really have no idea why in the last reply of yours the compose file complains...

Tapping in the dark, if you keep the True/False with apostrophes, what does the debug log say? Ie:
```
     REMOVE_FAILED_IMPORTS: "True"
     REMOVE_ORPHANS: "True"

```

**Comment by imran0** [comment]
It might be because I'm using an older version of Docker v20.10.3 (its the latest one my NAS supports). Using double quote does work because I can see in the logs the following:
```
[INFO   ]: False | Removing failed downloads (REMOVE_FAILED)
[INFO   ]: False | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO   ]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO   ]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO   ]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO   ]: False | Removing slow downloads (REMOVE_SLOW)
[INFO   ]: False | Removing stalled downloads (REMOVE_STALLED)
[INFO   ]: False | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
```

It's been a few days, looks like the items have been removed from Sonarr instance, I'm not really sure how. I have another Sonarr instance however which is showing the same issue.
![image](https://github.com/user-attachments/assets/d4ac6b43-bc52-4d7b-9023-8d29846bfd7d)
![image](https://github.com/user-attachments/assets/d919401d-143f-4a70-9578-7162bfb8cc87)

This is attached to another version of decluttarr. Here are the logs:
```
2024-10-19T14:42:08.983745949Z [VERBOSE]: Cleaning queue on Radarr RD:
2024-10-19T14:42:09.050505752Z [VERBOSE]: >>> Queue is clean.
2024-10-19T14:42:09.214252799Z [VERBOSE]: >>> Rescan: All missing items have recently been scanned for, thus nothing to rescan.
2024-10-19T14:42:10.231067487Z [VERBOSE]: >>> Running a scan for 1 cutoff items:
2024-10-19T14:42:10.231506445Z Albert (2016)
2024-10-19T14:42:10.338912616Z [VERBOSE]: Cleaning queue on Sonarr RD:
2024-10-19T14:42:10.403264234Z [VERBOSE]: >>> Queue is empty.
2024-10-19T14:42:10.848020638Z [VERBOSE]: >>> Running a scan for 1 missing items:
2024-10-19T14:42:10.848171745Z All Elite Wrestling: Dynamite (Season 2 / Episode 16 / Aired: 2020-04-15): AEW Dynamite 28
2024-10-19T14:42:11.148113786Z [VERBOSE]: >>> Running a scan for 1 cutoff items:
2024-10-19T14:42:11.148245061Z Cobra Kai (Season 5 / Episode 7 / Aired: 2022-09-09): Bad Eggs
2024-10-19T14:42:11.159915924Z [VERBOSE]: 
2024-10-19T14:42:11.160057313Z [VERBOSE]: Queue clean-up complete!
```

Here is the docker setup for that instance:

```
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    networks: 
      mediaNet:
        ipv4_address: 172.18.0.71
    hostname: decluttarr    
    restart: unless-stopped
    environment:
      PUID: 1028
      PGID: 65537
      TZ: Europe/London
      ## General
      # TEST_RUN: "True"
      # SSL_VERIFICATION:False
      LOG_LEVEL: VERBOSE
      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: "False"
      REMOVE_FAILED_IMPORTS: "True"
      REMOVE_METADATA_MISSING: "True"
      REMOVE_MISSING_FILES: "True"
      REMOVE_ORPHANS: "False"
      REMOVE_SLOW: "False"
      REMOVE_STALLED: "False"
      REMOVE_UNMONITORED: "False"
      RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 1, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 1, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'
      # Feature Settings
      PERMITTED_ATTEMPTS: 3
      # FAILED_IMPORT_MESSAGE_PATTERNS: '
      #   [
      #     "Not a Custom Format upgrade for existing", 
      #     "Not an upgrade for existing"
      #   ]'
```
