### ISSUE TITLE
[Sticky Thread| Docker Compose Examples

### ISSUE THREAD

**Issue by markhaines** [ManiMatter/decluttarr#173]
Can I offer this as an updated docker compose example for the instructions page - tested as working with Dockge (needs RUN_PERIODIC_RESCANS structured on a single line and uses - & = environment variable syntax:

version: "3.8"
services:
  decluttarr:
    container_name: decluttarr
    image: ghcr.io/manimatter/decluttarr:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - SSL_VERIFICATION=True
      - LOG_LEVEL=INFO
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Protected
      - MIN_DOWNLOAD_SPEED=50
      - RUN_PERIODIC_RESCANS={"SONARR":{"MISSING":true,"CUTOFF_UNMET":true,"MAX_CONCURRENT_SCANS":10,"MIN_DAYS_BEFORE_RESCAN":7},"RADARR":{"MISSING":true,"CUTOFF_UNMET":true,"MAX_CONCURRENT_SCANS":10,"MIN_DAYS_BEFORE_RESCAN":7}}
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not a Custom Format upgrade for
        existing", "Not an upgrade for existing"]
      - RADARR_URL=http(s)://<URL>:<PORT>
      - RADARR_KEY=<KEY>
      - SONARR_URL=http(s)://<URL>:<PORT>
      - SONARR_KEY=<KEY>
      - QBITTORRENT_URL=http(s)://<URL>:<PORT>
      - QBITTORRENT_USERNAME=<USER>
      - QBITTORRENT_PASSWORD=<PASSWORD>

**Comment by ManiMatter** [comment]
### **For anyone: Please share working docker-compose examples**
There are different dialects for yaml. Please feel free to add more examples of docker composes that work for you to this thread that may help others.

Please do not use it to ask questions about docker-composes (create own issues if you don't find the answer to your specific problem in this thread or other closed issues)

**Comment by bryancowell** [comment]
Thanks @markhaines

**Comment by gregeeh** [comment]
Here's mind that works in Portainer:

```
---
services:
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: Australia/Sydney
      PUID: 1000
      PGID: 100

      ## General
      # TEST_RUN=True
      # SSL_VERIFICATION=False
      LOG_LEVEL: INFO

      ## Features

      REMOVE_TIMER: 10
      REMOVE_FAILED: true
      REMOVE_FAILED_IMPORTS: true
      REMOVE_METADATA_MISSING: true
      REMOVE_MISSING_FILES: true
      REMOVE_ORPHANS: true
      REMOVE_SLOW: true
      REMOVE_STALLED: true
      REMOVE_UNMONITORED: true
      RUN_PERIODIC_RESCANS: ' { "SONARR": {"MISSING": true, "CUTOFF_UNMET": true,
        "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}, "RADARR":
        {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3,
        "MIN_DAYS_BEFORE_RESCAN": 7} }'
      
      # Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: '
         [
            "Not a Custom Format upgrade for existing",
            "Not an upgrade for existing",
            "Invalid video file"
         ]'
      
      ## Radarr
      RADARR_URL: $R_URL
      RADARR_KEY: $RADARR_API_KEY

      ## Sonarr
      SONARR_URL: $S_URL
      SONARR_KEY: $SONARR_API_KEY

      ## Qbittorrent
      QBITTORRENT_URL: $Q_URL
      QBITTORRENT_USERNAME: $USERNAME
      QBITTORRENT_PASSWORD: $PASSWD

```

**Comment by mpking828** [comment]
[gregeeh](https://github.com/gregeeh)'s worked for my Synology using Container Manager

**Comment by dwightmulcahy** [comment]
Ok, I got this working on QNAP Container Station 3... 

```yaml
version: "3.3"
services:
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago

      - SSL_VERIFICATION=True
      - LOG_LEVEL=INFO
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Protected
      - MIN_DOWNLOAD_SPEED=50
      - RUN_PERIODIC_RESCANS={"SONARR":{"MISSING":true,"CUTOFF_UNMET":true,"MAX_CONCURRENT_SCANS":10,"MIN_DAYS_BEFORE_RESCAN":7},"RADARR":{"MISSING":true,"CUTOFF_UNMET":true,"MAX_CONCURRENT_SCANS":10,"MIN_DAYS_BEFORE_RESCAN":7}}
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not a Custom Format upgrade for existing", "Not an upgrade for existing", "Invalid video file"]
      - RADARR_URL=http://radarr:7878
      - RADARR_KEY=<YOUR_API_KEY>
      - SONARR_URL=http://sonarr:8989
      - SONARR_KEY=<YOUR_API_KEY>
      - READARR_URL=http://readarr:8787
      - READARR_KEY=<YOUR_API_KEY>
    restart: always
```
