### ISSUE TITLE
example yaml file error on line 1 with docker compose

### ISSUE THREAD

**Issue by TheStumpChunkman** [ManiMatter/decluttarr#195]
I am trying to implement decluttarr in docker desktop on my Mac. I took the example yml and when I run the docker-compose up -d command in the folder where I put the yml file I get this error:

yaml: line 1: did not find expected ',' or '}'

Line 1 is just this:

version: "3.3"

Full yml file below: api keys and other sensitive info removed

version: "3.3"
services:
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
     TZ=America/Detroit
     PUID=1000
     PGID=1000

     ## General
     TEST_RUN=True
     SSL_VERIFICATION=False
     LOG_LEVEL: INFO

     ## Features 
     REMOVE_TIMER: 10
     REMOVE_FAILED: True
     REMOVE_FAILED_IMPORTS: True
     REMOVE_METADATA_MISSING: True
     REMOVE_MISSING_FILES: True
     REMOVE_ORPHANS: True
     REMOVE_SLOW: True
     REMOVE_STALLED: True
     REMOVE_UNMONITORED: True
     RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'

     # Feature Settings
     PERMITTED_ATTEMPTS: 10
     NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
     REMOVE_SLOW: True
     MIN_DOWNLOAD_SPEED: 100     
     FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]'

     ## Radarr
     RADARR_URL: http://localhost:7878
     RADARR_KEY:

     ## Sonarr
     SONARR_URL: http://localhost:8989
     SONARR_KEY:

     ## Lidarr
     ## LIDARR_URL=http://lidarr:8686
     ## LIDARR_KEY=$LIDARR_API_KEY

     ## Readarr
     ## READARR_URL=http://readarr:8787
     ## READARR_KEY=$READARR_API_KEY\

     ## Whisparr
     ## WHISPARR_URL=http://whisparr:6969
     ## WHISPARR_KEY=$WHISPARR_API_KEY

     ## qBitorrent
     QBITTORRENT_URL: http://localhost:8181
     # QBITTORRENT_USERNAME=
     # QBITTORRENT_PASSWORD=

**Comment by TheStumpChunkman** [comment]
I ran the file through a linter and is spit out a ton of issues.

All mapping items must start at the same column at line 13, column 1
Implicit keys need to be on a single line at line 13, column 6
All mapping items must start at the same column at line 18, column 1
All mapping items must start at the same column at line 19, column 1
All mapping items must start at the same column at line 20, column 1
All mapping items must start at the same column at line 21, column 1
All mapping items must start at the same column at line 22, column 1
All mapping items must start at the same column at line 23, column 1
All mapping items must start at the same column at line 24, column 1
All mapping items must start at the same column at line 25, column 1
All mapping items must start at the same column at line 26, column 1
All mapping items must start at the same column at line 27, column 1
All mapping items must start at the same column at line 34, column 1
All mapping items must start at the same column at line 35, column 1
All mapping items must start at the same column at line 36, column 1
Map keys must be unique at line 36, column 6
All mapping items must start at the same column at line 37, column 1
All mapping items must start at the same column at line 38, column 1
All mapping items must start at the same column at line 45, column 1
All mapping items must start at the same column at line 46, column 1
All mapping items must start at the same column at line 49, column 1
All mapping items must start at the same column at line 50, column 1
All mapping items must start at the same column at line 53, column 1
Implicit keys need to be on a single line at line 53, column 6
Implicit map keys need to be followed by map values at line 53, column 6
All mapping items must start at the same column at line 57, column 6
Implicit keys need to be on a single line at line 61, column 6
Implicit map keys need to be followed by map values at line 61, column 6

**Comment by ManiMatter** [comment]
Have you checked the closed issues for yaml examples?

**Comment by TheStumpChunkman** [comment]
I have not, I will go look there - thank you for the suggestion. I am not yet super experienced with Docker - have a few containers running but they are pretty simple - I will keep digging for info in the closed issues. Thanks.

**Comment by ezrarieben** [comment]
Docker compose files are based on YAML. Indentation is very important when formatting a YAML file.
Make sure the indentation is correct. 

Also, when defining environment variables in your docker compose as a list, you need to prefix the list items with `-`:

```yaml
  environment:
    - TZ=America/Detroit
    - PUID=1000
    - PGID=1000
```
If you define them as a mapping, you need to use `:` instead of `=`:
```yaml
  environment:
    TZ: America/Detroit
    PUID: 1000
    PGID: 1000
```

Stick to either or don't mix...

This is what your `docker-compose.yaml` should look like:

```yaml
version: "3.3"

services:
  decluttarr:
  image: ghcr.io/manimatter/decluttarr:latest
  container_name: decluttarr
  restart: always
  environment:
    TZ: America/Detroit
    PUID: 1000
    PGID: 1000

    ## General
    TEST_RUN: True
    SSL_VERIFICATION: False
    LOG_LEVEL: INFO

    ## Features 
    REMOVE_TIMER: 10
    REMOVE_FAILED: True
    REMOVE_FAILED_IMPORTS: True
    REMOVE_METADATA_MISSING: True
    REMOVE_MISSING_FILES: True
    REMOVE_ORPHANS: True
    REMOVE_SLOW: True
    REMOVE_STALLED: True
    REMOVE_UNMONITORED: True
    RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'

    # Feature Settings
    PERMITTED_ATTEMPTS: 10
    NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
    MIN_DOWNLOAD_SPEED: 100     
    FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]'

    ## Radarr
    RADARR_URL: http://localhost:7878
    RADARR_KEY:

    ## Sonarr
    SONARR_URL: http://localhost:8989
    SONARR_KEY:

    ## Lidarr
    ## LIDARR_URL=http://lidarr:8686
    ## LIDARR_KEY=$LIDARR_API_KEY

    ## Readarr
    ## READARR_URL=http://readarr:8787
    ## READARR_KEY=$READARR_API_KEY\

    ## Whisparr
    ## WHISPARR_URL=http://whisparr:6969
    ## WHISPARR_KEY=$WHISPARR_API_KEY

    ## qBitorrent
    QBITTORRENT_URL: http://localhost:8181
    # QBITTORRENT_USERNAME=
    # QBITTORRENT_PASSWORD=
 ```
