### ISSUE TITLE
YAML Format issues

### ISSUE THREAD

**Issue by egadgetboy** [ManiMatter/decluttarr#206]
People are having difficulty with the Compose file provided because it is not formatted correctly - please fix

Example:
https://www.reddit.com/r/sonarr/comments/1grvyje/cleanuperr_vs_decluttarr_and_install_guides_for/

Correctly formatted:

```
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000

      ## General
      # TEST_RUN=True
      # SSL_VERIFICATION=False
      LOG_LEVEL: INFO

      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: True
      REMOVE_FAILED_IMPORTS: True
      REMOVE_METADATA_MISSING: True
      REMOVE_MISSING_FILES: True
      REMOVE_ORPHANS: True
      REMOVE_SLOW: True
      REMOVE_STALLED: True
      REMOVE_UNMONITORED: True
      RUN_PERIODIC_RESCANS: '
        {
        "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
        "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'

      # Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: '[
        "Not a Custom Format upgrade for existing", 
        "Not an upgrade for existing"
      ]'

      ## Radarr
      RADARR_URL: http://192.168.1.220:7878
      RADARR_KEY: blah

      ## Sonarr
      SONARR_URL: http://192.168.1.220:8989
      SONARR_KEY: blah
```
