### ISSUE TITLE
Stalled downloads not removed

### ISSUE THREAD

**Issue by pl4za** [ManiMatter/decluttarr#225]
Hi, 

I can't seem to figure out why my stalled downloads are not getting removed...
They are monitored and marked as stalled in both sonarr and qbitorrent.
Running latest version of everything.

Here's my docker compose:
```
decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: unless-stopped
    network_mode: service:wireguard-client
    environment:
      TZ: Europe/Zurich
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: DEBUG
      ## Features
      REMOVE_TIMER: 10
      REMOVE_FAILED: true
      REMOVE_FAILED_IMPORTS: true
      REMOVE_METADATA_MISSING: true
      REMOVE_MISSING_FILES: true
      REMOVE_ORPHANS: true
      REMOVE_SLOW: true
      REMOVE_STALLED: true
      REMOVE_UNMONITORED: true
      RUN_PERIODIC_RESCANS: '
        {
        "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
        "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
        "Not a Custom Format upgrade for existing",
        "Not an upgrade for existing"
        ]'
      ## Radarr
      RADARR_URL: http://192.168.1.2:7878
      RADARR_KEY: 123
      ## Sonarr
      SONARR_URL: http://192.168.1.2:8989
      SONARR_KEY: 123
      ## qBitorrent
      QBITTORRENT_URL: http://192.168.1.2:9091
      QBITTORRENT_USERNAME: abc 
      QBITTORRENT_PASSWORD: 123
```

And a sample log: https://pastebin.com/gjWCBb08

Any help appreciated! 
Thanks
