### ISSUE TITLE
[v2] 'remove_orphans' triggered

### ISSUE THREAD

**Issue by balgerion** [ManiMatter/decluttarr#259]
I'm not sure if this is an issue or if I'm just misunderstanding something, but whenever Sonarr finds an upgrade for my anime, Decluttarr marks it as an orphan and is killing it on sight.

![Image](https://github.com/user-attachments/assets/c171237e-1ebe-4d4d-b459-22aaa685a7fa)

Anime is downloaded and marked to monitor. 
![Image](https://github.com/user-attachments/assets/a8e402cd-c07d-400b-873c-75e781377163)
I've seen similar behavior a few times.

and in this situation 

![Image](https://github.com/user-attachments/assets/790be0e7-6f4c-4b09-a9af-8c02aab5d8a0)

i think it should use  "REMOVE_FAILED_IMPORTS"

**Comment by ManiMatter** [comment]
Can you show a screenshot of your queue pls?

**Comment by balgerion** [comment]
This is only file in queue

![Image](https://github.com/user-attachments/assets/d24f8b29-d3f1-42bd-8a82-631490f26bc5)

**Comment by ManiMatter** [comment]
Yeah. strange.

Can you please do the following:
- Put all jobs to false except for remove_orphans and remove_failed_imports
- Switch to debug logs and post them in a pastebin

**Comment by balgerion** [comment]
Sure, I will paste it when I catch something

**Comment by balgerion** [comment]
https://pastebin.com/B8E0FHXW    - all of the remove orphan from the past two hours 

all of them are "Not a Custom Format upgrade for existing episode" or "Not an upgrade for existing episode file(s"

![Image](https://github.com/user-attachments/assets/5d14053a-e7d9-42a1-96ac-ebacb016034e)

**Comment by ookla-ariel-ride** [comment]
This seems like a sonarr CF issue and not a decluttarr issue.  Are you following trash guides Quality profiles and naming suggestions?

**Comment by balgerion** [comment]
Yup , recyclar is syncing daily. But why this is „orphan” ? It shouldn’t be failed import ?

**Comment by ManiMatter** [comment]
could you please paste your settings?
did you use test_run when you posted the above logs? i can't see any DELETE calls

**Comment by ManiMatter** [comment]
I just pushed another version that will give more logs (also when run as test_run).
Can you please fetch it and provide another set of logs? Many thanks

**Comment by balgerion** [comment]
I will fetch and install new version in a sec
config:
```
general:
  log_level: DEBUG
  test_run: true
  timer: 20
  # ignored_download_clients: ["emulerr"]
  # ssl_verification: false # Optional: Defaults to true
  # private_tracker_handling: "obsolete_tag" # remove, skip, obsolete_tag. Optional. Default: remove
  # public_tracker_handling: "remove"  # remove, skip, obsolete_tag. Optional. Default: remove
  # obsolete_tag: "Obsolete" # optional. Default: "Obsolete"
  # protected_tag: "Keep" # optional. Default: "Keep"

job_defaults:
  max_strikes: 3
  min_days_between_searches: 7
  max_concurrent_searches: 3

jobs:
  remove_bad_files: false
  # keep_archives: true

  remove_failed_downloads: false

#  remove_failed_imports:
#    message_patterns:
#      - Not a Custom Format upgrade for existing*
#      - Not an upgrade for existing*

  remove_metadata_missing: false
  # max_strikes: 3

  remove_missing_files: false

  remove_orphans: true

  remove_slow:
    min_speed: 200
    max_strikes: 3

  remove_stalled: false
  # max_strikes: 3

  remove_unmonitored: false

  search_unmet_cutoff_content: false
  # min_days_between_searches: 7
  # max_concurrent_searches: 3

  search_missing_content: false
  # min_days_between_searches: 7
  # max_concurrent_searches: 3

instances:
  sonarr:
    - base_url: "http://arr-suite-sonarr:8989"
      api_key: ""
    - base_url: "http://arr-suite-sonarr-anime:9898"
      api_key: ""
  radarr:
    - base_url: "http://arr-suite-radarr:7878"
      api_key: ""
    - base_url: "http://arr-suite-radarr-anime:7979"
      api_key: ""
  readarr:
    - base_url: "http://arr-suite-readarr:8787"
      api_key: ""
  lidarr:
    - base_url: "http://arr-suite-lidarr:8686"
      api_key: ""

download_clients:
  qbittorrent:
    - base_url: "http://arr-suite-gluetun:8080"
      username: balgerion
      password: WojnA666#
      name: "qBittorrent"
    - base_url: "http://arr-suite-gluetun:8088"
      username: balgerion
      password: WojnA666#
      name: "qBittorrent-seeder"
```
