### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Shane091490** [ManiMatter/decluttarr#76]
Hi again,

Still having issue with trying to get decluttarr to run with sonarr.  I submitted this before but I was in the process of moving and had to shutdown my server and couldn't get back with you. I tried pulling a new image but still getting the same error.

Still no change, still getting same error...

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

Using the below docker compose:

version: "3.3"
services:
  sonarr-decluttarr:
    image: ghcr.io/manimatter/decluttarr:dev
    container_name: sonarr-decluttarr
    restart: always
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      ## General
      - LOG_LEVEL=DEBUG
      #- TEST_RUN=True
      #- SSL_VERIFICATION=False
      ## Features 
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=False
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      #- MIN_DOWNLOAD_SPEED=100
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - IGNORE_PRIVATE_TRACKERS=False
      ## Sonarr
      - SONARR_URL=https://sonarr.myrealm.site
      - SONARR_KEY=Removed
      ## qBittorrent
      - QBITTORRENT_URL=https://sqbit.myrealm.site
      - QBITTORRENT_USERNAME=Removed
      - QBITTORRENT_PASSWORD=Removed

**Comment by ManiMatter** [comment]
Delete all decluttarr images and containers that you may have already

then pull latest

im 99% sure it will then run

let me know, cheers

**Comment by Shane091490** [comment]
After clearing out the old images and pulling new image it started working. 

Thanks.

**Comment by ManiMatter** [comment]
Great! If you dont already have it, you may be interested in a watchtower, which does automated upgrades to your containers.

here's my config, just for your reference in case interested.

```
# WatchTower - Automatic Docker Container Updates
 watchtower:
   <<: *common-keys-core
   image: containrrr/watchtower:latest
   container_name: watchtower
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
   environment:
     WATCHTOWER_CLEANUP: "true"
     WATCHTOWER_REMOVE_VOLUMES: "true"
     WATCHTOWER_INCLUDE_STOPPED: "true"
     WATCHTOWER_NO_STARTUP_MESSAGE: "false"
     WATCHTOWER_SCHEDULE: "0 26 12 * * *" # Everyday at 12:30
     DOCKER_API_VERSION: "1.40"
     <<: *default-tz-puid-pgid
```
